### ISSUE TITLE
Slides: Henrik Bengtsson, Futures (2020-01-29)

### ISSUE THREAD

**Issue by HenrikBengtsson** [EmilHvitfeldt/RStudioConf2020Slides#9]
My slides in the "16:00 Session 3, Track 4: Programming" session:
* https://www.jottr.org/2020/02/01/future-rstudioconf2020-slides/

**Comment by EmilHvitfeldt** [comment]
Thank you!

**Comment by HenrikBengtsson** [comment]
Thank *you* for putting this together
